### ISSUE TITLE
添加Gists配置文件备份和同步功能

### ISSUE THREAD

**Issue by New2en** [proxy-rock/proxy-rock#3]
之前 用过一个书签同步的工具 https://github.com/dudor/BookmarkHub
可以通过 GitHub gists 备份和同步配置，觉得很好用，希望可以考虑加入

SwitchyOmega 也有备份功能，但缺少多浏览器在线同步备份的功能，感
觉GitHub gists 就是一个很好的解决方案

**Comment by proxy-rock** [comment]
是个好想法，回头评估下看~
