### ISSUE TITLE
添加的代理页面有空白，不能删除，提示已绑定。

### ISSUE THREAD

**Issue by snipertulip** [proxy-rock/proxy-rock#4]
昨天还好好的，今天添加的代理设置页面里，目测无法解析配置文件，没有之前添加的代理地址和端口，也不能删除，即使删除了Auto模式绑定也不行

**Comment by proxy-rock** [comment]
不能删除，应该是这条 Rule 被其他 Rule 依赖了，可以确认下看。
另外计划在未来的版本，在提示框里添加依赖详情。

**Comment by snipertulip** [comment]
> 不能删除，应该是这条 Rule 被其他 Rule 依赖了，可以确认下看。 另外计划在未来的版本，在提示框里添加依赖详情。

其他Rule都删除了，没有依赖，是个bug，不知道怎么出现的，奇怪。

**Comment by snipertulip** [comment]
> 不能删除，应该是这条 Rule 被其他 Rule 依赖了，可以确认下看。 另外计划在未来的版本，在提示框里添加依赖详情。

老兄，ZeroOmega插件V3已经出来了，So...

**Comment by proxy-rock** [comment]
> > 不能删除，应该是这条 Rule 被其他 Rule 依赖了，可以确认下看。 另外计划在未来的版本，在提示框里添加依赖详情。
> 
> 老兄，ZeroOmega插件V3已经出来了，So...

😂 多个选择总不是坏事

**Comment by snipertulip** [comment]
> > > 不能删除，应该是这条 Rule 被其他 Rule 依赖了，可以确认下看。 另外计划在未来的版本，在提示框里添加依赖详情。
> > 
> > 
> > 老兄，ZeroOmega插件V3已经出来了，So...
> 
> 😂 多个选择总不是坏事

总之，自己动手丰衣足食！👍

**Comment by snipertulip** [comment]
> > > 不能删除，应该是这条 Rule 被其他 Rule 依赖了，可以确认下看。 另外计划在未来的版本，在提示框里添加依赖详情。
> > 
> > 
> > 老兄，ZeroOmega插件V3已经出来了，So...
> 
> 😂 多个选择总不是坏事

总之，自己动手丰衣足食！👍
